### ISSUE TITLE
너무 좋은 서비스인 것 같아요 👍 

### ISSUE THREAD

**Issue by khwoowoo** [woorifisa-service-dev-3rd/frontend-1st-HHN#11]
좋은 서비스 잘 봤습니다 😄 
근데, 항목을 클릭해야 정보가 나오는 것 같은데
처음 사용하는 사용자라면 항목을 클릭해야 되는 것인지 모를 것 같습니다!
만약 한다면 커서 포인터 변경하거나 디자인적으로 클릭할 수 있도록 유도하시면 좋을 것 같아요!

**Comment by Jieun-KWAK** [comment]
말씀하신 커서 포인터 변경하거나 디자인적으로 클릭할 수 있도록 유도하는 구현 방법도 생각해보겠습니다
좋은 의견 감사합니다 !!
