### ISSUE TITLE
triple-roulette-review

### ISSUE THREAD

**Issue by qbobl5** [woorifisa-service-dev-3rd/frontend-1st-HHN#12]
1. 토글 항목 클릭할 때 커서가 텍스트 선택 모양이라서 사용자가 클릭할 수 있는지 아닌지 헷갈릴 수 있을 것 같아요. 커서를 포인터로 하시면 더 직관적일 것 같습니다.
2. 메인 화면의 사진 크기를 더 키우시면 좋을 것 같습니다.

**Comment by Jieun-KWAK** [comment]
말씀하신 토글 항목 클릭할 때 커서와 메인 화면의 사진 크기 수정해보겠습니다
리뷰 감사합니다 !!
