### ISSUE TITLE
ppl-review

### ISSUE THREAD

**Issue by jyp-on** [woorifisa-service-dev-3rd/frontend-1st-HHN#14]
팀원마다 상단의 기본정보는 통일하는게 깔끔할 것 같아요!
또한 팀원마다 소개글 박스 크기가 달라져서 통일 되었으면 좋을 것 같아요

**Comment by Jieun-KWAK** [comment]
팀원마다 자유롭게 작성하고자 소개글 박스 양식을 통일하지 않았는데 통일하면 더 깔끔하게 구성할 수 있을 것 같습니다
리뷰 감사합니다 !!
