### ISSUE TITLE
자기 소개를 하기에 좋은 페이지인 것 같습니다! 질문 있어요

### ISSUE THREAD

**Issue by my123dsa** [woorifisa-service-dev-3rd/frontend-1st-HHN#17]
1. 개인 페이지에 들어가면 상단바 내용이 그 사람의 이름으로 변하는데 구자빈 님의 페이지는 팀소개로 되어있습니다. 
확인해보시면 좋을 것 같아요!

2. 혹시 상단 페이지명이 바뀌는 건 어떤 코드를 적용시키셨는지 궁금합니다!

3. 팀 로고에 특별한 의미가 있는지 궁금합니다!

**Comment by Jieun-KWAK** [comment]
1, 2. 상단 페이지명은 개별로 작성하고 양식을 통일하지 않아서 바뀌는 것처럼 보였을 것 같습니다
        코드는 <title>로 작성하였습니다
3. 팀 로고에 특별한 의미는 없습니다 !
