### ISSUE TITLE
[강김길] 잘 봤습니다 !

### ISSUE THREAD

**Issue by rlfrkdms1** [woorifisa-service-dev-3rd/frontend-1st-HHN#18]
팀원들 소개 잘 봤습니다. 😀
- 토글에 토글이라는 표시가 있으면 좋을 것 같습니다. 
- [지은님 페이지](https://woorifisa-service-dev-3rd.github.io/frontend-1st-HHN/cover_letter/jieun.html) `title container` 클래스에 margin-top이 잡혀있어서 사진위에 큰 공백이 있는데 이유가 있는지 궁금합니다. 
- `깃허브: 깃허브로 이동`이 아닌 깃허브 이모티콘을 누르면 이동한다던가의 방식도 좋을 것 같습니다.

**Comment by Jieun-KWAK** [comment]
여백의 미를 강조하고 싶어서 사진 위 공백을 두었습니다 !
토글 표시와 깃허브로 이동할 때 아이콘 사용하는 디자인 좋을 것 같습니다 !
자세한 리뷰 감사합니다
