### ISSUE TITLE
피드백:)

### ISSUE THREAD

**Issue by kh-0818** [woorifisa-service-dev-3rd/frontend-1st-HHN#19]
각자 자기소개를 하는게 좋긴한데 항목을 각 개인이 추가하는 것보다는 통일성을 갖춰주는게 좋을 것 같다고 생각합니다!

**Comment by Kee0304** [comment]
기획 시, 각자의 개성을 나타내고자 디자인부터 내용까지 자유롭게 작성하기로 결정했는데 다른 분들이 보기엔 레이아웃이 통일되지 않아 서비스에 집중하기 어려웠던 것으로 보입니다. 해당 페이지가 서비스로 고도화된다면 통일을 고려해보겠습니다.
감사합니다.
